
version: 2.1 
 
orbs:
  common: eddiewebb/common_tasks@0.1.0
 
workflows:
  basic:
    jobs:
      - common/common_task:
          task-name: demo-task
          pre-steps:
           - run: echo \"export SOME_VAR=value\" >> $BASH_ENV
