version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - gcp-kms/gcr-auth
    - run:
        command: >
          gcloud kms decrypt \
              --ciphertext-file "path to ciphertext-file" \
              --plaintext-file "path to plaintext-file" \
              --location global \
              --keyring $KMS_KEYRING \
              --key $KMS_KEY
workflows:
  example-workflow:
    jobs:
      - build:
          context: gcloud
