version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: echo "Hello World"
      - run: sleep 5
  test1:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: echo "World says Hel"
      - run: sleep 5
  test2:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: echo "World says lo"
      - run: sleep 5

  deploy:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: echo "Ending conversation now"
      - run: sleep 5
         
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - deploy:
          requires:
            - test1
            - test2
