version: 2.1
jobs:
  build:
    parameters:
      sdk-version:
        description: "Version for android"
        type: string
    docker:
      - image: circleci/android:<< parameters.sdk-version >>
    steps:
      - checkout
      
workflows:
  my-workflow:
    jobs:
      - build:
          sdk-version: "api-26"
          name: build-api26
      - build:
          sdk-version: "api-27"
          name: build-api27
      - build:
          sdk-version: "api-28"
          name: build-api28
      - build:
          sdk-version: "api-29"
          name: build-api29
