version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: echo "Hello World"
      - run: sleep 5
  test:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: echo "World says Hello"
      - run: sleep 5
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          # only run this job if build succeeds
          requires:
            - build 
