version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - run: echo $GCLOUD_SERVICE_KEY
    - gcp-kms/gcr-auth
    - gcp-kms/get-decrypt
   
workflows:
  sample-workflow:
    jobs:
      - build:
          context: myContext
