version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/node:11.10.1-browsers 
    steps:
      - checkout
      - run: echo "Build Job"
  unit-test:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "Unit Test Job"
  spotless:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "Spotless Job"   
  sonarqube:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: |
            if [ "$CIRCLE_BRANCH" = "develop" ]; then
                circleci-agent step halt
            fi
      - run: echo "Run SonarQube"
  deploy-to-qa:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "Deploy to QA"
  deploy-to-prod:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "Deploy to Production"
workflows:
  version: 2
  sample-workflow:
    jobs:
      - build       
      - unit-test:     
          requires:
            - build
      - spotless:     
          requires:
            - build
      - sonarqube:     
          requires:
            - unit-test
            - spotless
      - deploy-to-qa:
          filters:
            branches:
              only: qa      
          requires:
            - sonarqube
      - deploy-to-prod:
          filters:
            branches:
              only: master     
          requires:
            - sonarqube            
