version: 2.1
jobs:
  bar:
    docker:
      - image: ubuntu:latest 
    steps:
      - checkout
      - run:
          command: |
            public_ip_address=$(wget -qO- http://checkip.amazonaws.com)
            echo "this computers public ip address is $public_ip_address"
workflows:
  build:
    jobs:
      - bar
