version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - gcp-kms/gcr-auth
    - gcp-kms/get-decrypt:
        ciphertext-file: "mysecret.txt.encrypted"
        plaintext-file: "mysecret.txt.decrypted"
        object-path: "mysecret.txt.encrypted"
workflows:
  example-workflow1:
    jobs:
      - build:
          context: gcloud
