version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - gcp-kms/gcr-auth:
        gcloud-service-key: $GCLOUD_SERVICE_KEY
        google-compute-zone: $GOOGLE_COMPUTE_ZONE
        google-project-id: $GOOGLE_PROJECT_ID
    - gcp-kms/get-decrypt:
        ciphertext-file: $CIPHERTEXT_FILE
        plaintext-file: $PLAINTEXT_FILE
        location: $LOCATION
        keyring: $KEYRING
        key: $KEY
        bucket: $BUCKET
        object-path: $OBJECT_PATH
workflows:
  sample-workflow:
    jobs:
      - build:
          context: myContext
