version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
    - checkout
    - run:
        command: |
          cat /sys/fs/cgroup/memory/memory.usage_in_bytes  | awk '{ byte =$1 /1024/1024/1024; print byte " GB" }'
          
workflows:
  example-workflow1:
    jobs:
      - build
