version: 2.1
jobs:
  bar:
    docker:
      - image: ubuntu:latest
    parallelism: 4  
    steps:
      - checkout
      - run:
          command: echo "building"
      - run:
          command: echo "testing"
workflows:
  build:
    jobs:
      - bar:
          post-steps:
            - run:
                command: echo "upload artifact to s3"
