version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - run: echo $GCLOUD_SERVICE_KEY
    - gcp-kms/gcr-auth
    - gcp-kms/get-decrypt:
        ciphertext-file: $CIPHERTEXT_FILE
        plaintext-file: $PLAINTEXT_FILE
        location: $LOCATION
        keyring: $KEYRING
        key: $KEY
        bucket: $BUCKET
        object-path: $OBJECT_PATH
workflows:
  sample-workflow:
    jobs:
      - build:
          context: myContext
