version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - gcp-kms/gcr-auth
    - run:
        command: |
          gsutil cp gs://priceline-testing-test-bucket-circle/mysecret.txt.encrypted .
          gcloud kms decrypt \
              --ciphertext-file mysecret.txt.encrypted \
              --plaintext-file mysecret.txt.decrypted \
              --location us \
              --keyring $KMS_KEYRING \
              --key $KMS_KEY
workflows:
  example-workflow1:
    jobs:
      - build:
          context: gcloud
