version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - gcp-kms/gcr-auth
    - run:
        command: |
          gsutil cp gs://$GOOGLE_PROJECT_ID-$<<parameters.bucket>>/<<parameters.object-path>> .
          gcloud kms decrypt \
              --ciphertext-file <<parameters.ciphertext-file>> \
              --plaintext-file <<parameters.plaintext-file>> \
              --location global \
              --keyring $<<parameters.keyring>> \
              --key $<<parameters.key>>
workflows:
  example-workflow1:
    jobs:
      - build:
          context: gcloud
