version: 2.1
orbs:
  gcp-kms: carecloud/gcp-kms@0.0.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
    - checkout
    - gcp-kms/gcr-auth
workflows:
  example-workflow:
    jobs:
      - build:
          context: gcloud
